### ISSUE TITLE
LithoSim training

### ISSUE THREAD

**Issue by thomashirtz** [shelljane/lithobench#6]
Hello!
Most of the deep learning models are using pylitho as ground truth. Is there a place where I can find the LithoSim training loop itself ?
Moreover, I can see that CFNO is using PixelILT data as training samples, but there are no comments on the origin of those files, Is it possible to know how they are generated ?

Thanks

**Comment by gaussiangit** [comment]
@thomashirtz did you figure out how those kernels are generated ? I believe provided from ICCAD 2013 but I could not find the source of it anywhere

**Comment by thomashirtz** [comment]
I believed I closed this issue because I found the answer about the training samples in their paper somewhere. As for the kernels, it is from ICCAD 2013, but I never found the original page.
